2019-04-25T21:15:53.457599+00:00 heroku[web.1]: State changed from up to down
2019-04-25T21:15:54.603213+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2019-04-25T21:15:54.622760+00:00 app[web.1]: [2019-04-25 21:15:54 +0000] [11] [INFO] Worker exiting (pid: 11)
2019-04-25T21:15:54.625326+00:00 app[web.1]: [2019-04-25 21:15:54 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-04-25T21:15:54.633787+00:00 app[web.1]: [2019-04-25 21:15:54 +0000] [4] [INFO] Handling signal: term
2019-04-25T21:15:54.737496+00:00 app[web.1]: [2019-04-25 21:15:54 +0000] [4] [INFO] Shutting down: Master
2019-04-25T21:15:54.872748+00:00 heroku[web.1]: Process exited with status 0
2019-04-25T21:35:51.503468+00:00 heroku[web.1]: Starting process with command `gunicorn app:app --log-file -`
2019-04-25T21:35:53.669880+00:00 heroku[web.1]: State changed from starting to crashed
2019-04-25T21:35:53.674713+00:00 heroku[web.1]: State changed from crashed to starting
2019-04-25T21:35:53.650145+00:00 heroku[web.1]: Process exited with status 3
2019-04-25T21:35:53.539527+00:00 app[web.1]: [2019-04-25 21:35:53 +0000] [4] [INFO] Starting gunicorn 19.9.0
2019-04-25T21:35:53.540973+00:00 app[web.1]: [2019-04-25 21:35:53 +0000] [4] [INFO] Listening at: http://0.0.0.0:54764 (4)
2019-04-25T21:35:53.541068+00:00 app[web.1]: [2019-04-25 21:35:53 +0000] [4] [INFO] Using worker: sync
2019-04-25T21:35:53.544916+00:00 app[web.1]: [2019-04-25 21:35:53 +0000] [10] [INFO] Booting worker with pid: 10
2019-04-25T21:35:53.550141+00:00 app[web.1]: [2019-04-25 21:35:53 +0000] [10] [ERROR] Exception in worker process
2019-04-25T21:35:53.550143+00:00 app[web.1]: Traceback (most recent call last):
2019-04-25T21:35:53.550145+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-04-25T21:35:53.550146+00:00 app[web.1]: worker.init_process()
2019-04-25T21:35:53.550147+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-04-25T21:35:53.550148+00:00 app[web.1]: self.load_wsgi()
2019-04-25T21:35:53.550149+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-04-25T21:35:53.550150+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-04-25T21:35:53.550152+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-04-25T21:35:53.550153+00:00 app[web.1]: self.callable = self.load()
2019-04-25T21:35:53.550154+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-04-25T21:35:53.550155+00:00 app[web.1]: return self.load_wsgiapp()
2019-04-25T21:35:53.550156+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-04-25T21:35:53.550157+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-04-25T21:35:53.550158+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2019-04-25T21:35:53.550159+00:00 app[web.1]: __import__(module)
2019-04-25T21:35:53.550161+00:00 app[web.1]: File "/app/app.py", line 32
2019-04-25T21:35:53.550162+00:00 app[web.1]: print form.errors
2019-04-25T21:35:53.550163+00:00 app[web.1]: ^
2019-04-25T21:35:53.550164+00:00 app[web.1]: SyntaxError: Missing parentheses in call to 'print'. Did you mean print(form.errors)?
2019-04-25T21:35:53.550263+00:00 app[web.1]: [2019-04-25 21:35:53 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-04-25T21:35:53.579003+00:00 app[web.1]: [2019-04-25 21:35:53 +0000] [4] [INFO] Shutting down: Master
2019-04-25T21:35:53.579069+00:00 app[web.1]: [2019-04-25 21:35:53 +0000] [4] [INFO] Reason: Worker failed to boot.
2019-04-25T21:35:57.075393+00:00 heroku[web.1]: Starting process with command `gunicorn app:app --log-file -`
2019-04-25T21:35:59.582776+00:00 heroku[web.1]: State changed from starting to crashed
2019-04-25T21:35:59.403550+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [4] [INFO] Starting gunicorn 19.9.0
2019-04-25T21:35:59.406043+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [4] [INFO] Listening at: http://0.0.0.0:56301 (4)
2019-04-25T21:35:59.406239+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [4] [INFO] Using worker: sync
2019-04-25T21:35:59.411250+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [10] [INFO] Booting worker with pid: 10
2019-04-25T21:35:59.418818+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [10] [ERROR] Exception in worker process
2019-04-25T21:35:59.418821+00:00 app[web.1]: Traceback (most recent call last):
2019-04-25T21:35:59.418824+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-04-25T21:35:59.418826+00:00 app[web.1]: worker.init_process()
2019-04-25T21:35:59.418827+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-04-25T21:35:59.418829+00:00 app[web.1]: self.load_wsgi()
2019-04-25T21:35:59.418831+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-04-25T21:35:59.418833+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-04-25T21:35:59.418834+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-04-25T21:35:59.418836+00:00 app[web.1]: self.callable = self.load()
2019-04-25T21:35:59.418838+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-04-25T21:35:59.418840+00:00 app[web.1]: return self.load_wsgiapp()
2019-04-25T21:35:59.418841+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-04-25T21:35:59.418843+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-04-25T21:35:59.418845+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2019-04-25T21:35:59.418846+00:00 app[web.1]: __import__(module)
2019-04-25T21:35:59.418848+00:00 app[web.1]: File "/app/app.py", line 32
2019-04-25T21:35:59.418849+00:00 app[web.1]: print form.errors
2019-04-25T21:35:59.418851+00:00 app[web.1]: ^
2019-04-25T21:35:59.418853+00:00 app[web.1]: SyntaxError: Missing parentheses in call to 'print'. Did you mean print(form.errors)?
2019-04-25T21:35:59.419101+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-04-25T21:35:59.452737+00:00 app[web.1]: Exception ignored in: <function _releaseLock at 0x7f1819885158>
2019-04-25T21:35:59.452744+00:00 app[web.1]: Traceback (most recent call last):
2019-04-25T21:35:59.452789+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/logging/__init__.py", line 221, in _releaseLock
2019-04-25T21:35:59.454556+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [11] [INFO] Booting worker with pid: 11
2019-04-25T21:35:59.458735+00:00 app[web.1]: def _releaseLock():
2019-04-25T21:35:59.458738+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
2019-04-25T21:35:59.458980+00:00 app[web.1]: self.reap_workers()
2019-04-25T21:35:59.458986+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2019-04-25T21:35:59.459335+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2019-04-25T21:35:59.459420+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2019-04-25T21:35:59.460174+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [11] [ERROR] Exception in worker process
2019-04-25T21:35:59.460177+00:00 app[web.1]: Traceback (most recent call last):
2019-04-25T21:35:59.460179+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-04-25T21:35:59.460181+00:00 app[web.1]: worker.init_process()
2019-04-25T21:35:59.460183+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-04-25T21:35:59.460184+00:00 app[web.1]: self.load_wsgi()
2019-04-25T21:35:59.460186+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-04-25T21:35:59.460188+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-04-25T21:35:59.460190+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-04-25T21:35:59.460191+00:00 app[web.1]: self.callable = self.load()
2019-04-25T21:35:59.460193+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-04-25T21:35:59.460195+00:00 app[web.1]: return self.load_wsgiapp()
2019-04-25T21:35:59.460197+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-04-25T21:35:59.460198+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-04-25T21:35:59.460200+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2019-04-25T21:35:59.460202+00:00 app[web.1]: __import__(module)
2019-04-25T21:35:59.460203+00:00 app[web.1]: File "/app/app.py", line 32
2019-04-25T21:35:59.460205+00:00 app[web.1]: print form.errors
2019-04-25T21:35:59.460207+00:00 app[web.1]: ^
2019-04-25T21:35:59.460208+00:00 app[web.1]: SyntaxError: Missing parentheses in call to 'print'. Did you mean print(form.errors)?
2019-04-25T21:35:59.460321+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [11] [INFO] Worker exiting (pid: 11)
2019-04-25T21:35:59.494859+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [4] [INFO] Shutting down: Master
2019-04-25T21:35:59.495050+00:00 app[web.1]: [2019-04-25 21:35:59 +0000] [4] [INFO] Reason: Worker failed to boot.
2019-04-25T21:35:59.567141+00:00 heroku[web.1]: Process exited with status 3
2019-04-25T21:36:05.778380+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=powerful-escarpment-88433.herokuapp.com request_id=0efbc27f-3237-450c-a1fe-f36f0862c6cf fwd="169.231.147.230" dyno= connect= service= status=503 bytes= protocol=https
Terminate batch job (Y/N)? 
Terminate batch job (Y/N)? 
Terminate batch job (Y/N)? 
